<a href="https://colab.research.google.com/github/souravk03/Machine-Learning-404/blob/main/Day_34_Handling_date_and_time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [6]:
time=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Datasets/messages.csv')
date=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Datasets/orders.csv')

In [7]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [8]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [10]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

#Working with Dates

In [12]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [14]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
 4   date_year   1000 non-null   int32
dtypes: datetime64[ns](1), int32(1), int64(3)
memory usage: 35.3 KB

In [13]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
621 2018-10-12        6011        9       4       2018
399 2019-10-13         149       14      37       2019
344 2018-12-22        7510       16       4       2018
361 2018-10-13         124       26       2       2018
64  2019-06-01        3541        2       5       2019

In [15]:
#1. Extract year
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
965 2019-05-13        1980        6       1       2019
95  2019-04-02        5383       11      24       2019
917 2019-01-25        1613       28       6       2019
529 2019-07-30        5698        0       1       2019
976 2019-04-18        5320       13       1       2019

In [16]:
#2. Extract Month
date['date_month_no'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [17]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

In [18]:
#Extract Days
date['date_day'] = date['date'].dt.day

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [19]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [20]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [21]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

In [24]:
#Extract week of the year
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

In [25]:
##Extract Quarter
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

In [26]:
#Extract Semester
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

In [29]:
#Extract Time elapsed between dates
import datetime

today = datetime.datetime.today()

today#

datetime.datetime(2025, 11, 30, 13, 18, 52, 232796)

In [30]:
today - date['date']

0     2182 days 13:18:52.232796
1     2664 days 13:18:52.232796
2     2595 days 13:18:52.232796
3     2297 days 13:18:52.232796
4     2520 days 13:18:52.232796
                 ...
995   2610 days 13:18:52.232796
996   2551 days 13:18:52.232796
997   2399 days 13:18:52.232796
998   2464 days 13:18:52.232796
999   2238 days 13:18:52.232796
Name: date, Length: 1000, dtype: timedelta64[ns]

In [31]:
(today - date['date']).dt.days

0      2182
1      2664
2      2595
3      2297
4      2520
       ...
995    2610
996    2551
997    2399
998    2464
999    2238
Name: date, Length: 1000, dtype: int64

In [39]:
# Months passed

# Calculate total months from a reference point for both today and each date in the 'date' column
today_months = today.year * 12 + today.month
date_months = date['date'].dt.year * 12 + date['date'].dt.month

# Calculate the difference in months
months_passed = today_months - date_months

# Round the result
np.round(months_passed, 0)

0      71
1      87
2      85
3      75
4      82
       ..
995    85
996    83
997    78
998    80
999    73
Name: date, Length: 1000, dtype: int32

In [40]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [41]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [42]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [43]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [44]:
#Extract Time part
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [45]:
#Time difference
today - time['date']

0     4368 days 12:28:52.232796
1     4232 days 13:38:52.232796
2     4718 days 12:57:52.232796
3     4020 days 12:47:52.232796
4     4417 days 14:07:52.232796
                 ...
995   5007 days 12:28:52.232796
996   4328 days 14:04:52.232796
997   4793 days 13:41:52.232796
998   4909 days 13:44:52.232796
999   4181 days 13:53:52.232796
Name: date, Length: 1000, dtype: timedelta64[ns]

In [46]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.774401e+08
1      3.656939e+08
2      4.076819e+08
3      3.473741e+08
4      3.816797e+08
           ...
995    4.326497e+08
996    3.739899e+08
997    4.141645e+08
998    4.241871e+08
999    3.612884e+08
Name: date, Length: 1000, dtype: float64

In [47]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.290669e+06
1      6.094899e+06
2      6.794698e+06
3      5.789568e+06
4      6.361328e+06
           ...
995    7.210829e+06
996    6.233165e+06
997    6.902742e+06
998    7.069785e+06
999    6.021474e+06
Name: date, Length: 1000, dtype: float64

In [48]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      104844.481176
1      101581.647842
2      113244.964509
3       96492.797842
4      106022.131176
           ...
995    120180.481176
996    103886.081176
997    115045.697842
998    117829.747842
999    100357.897842
Name: date, Length: 1000, dtype: float64