<a href="https://colab.research.google.com/github/souravk03/Machine-Learning-404/blob/main/Day_32_Binning%26Binarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Encoding numerical values into categorical values

##Binning/Descritization

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.preprocessing import Binarizer
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.compose import ColumnTransformer

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Datasets/train.csv')[['Age','Fare','SibSp','Parch','Survived']]
df

      Age     Fare  SibSp  Parch  Survived
0    22.0   7.2500      1      0         0
1    38.0  71.2833      1      0         1
2    26.0   7.9250      0      0         1
3    35.0  53.1000      1      0         1
4    35.0   8.0500      0      0         0
..    ...      ...    ...    ...       ...
886  27.0  13.0000      0      0         0
887  19.0  30.0000      0      0         1
888   NaN  23.4500      1      2         0
889  26.0  30.0000      0      0         1
890  32.0   7.7500      0      0         0

[891 rows x 5 columns]

In [ ]:
df.shape

(891, 5)

In [ ]:
df.isnull().sum()

Age         177
Fare          0
SibSp         0
Parch         0
Survived      0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

Age         0
Fare        0
SibSp       0
Parch       0
Survived    0
dtype: int64

In [ ]:
df.shape

(714, 5)

In [ ]:
df.head()

    Age     Fare  SibSp  Parch  Survived
0  22.0   7.2500      1      0         0
1  38.0  71.2833      1      0         1
2  26.0   7.9250      0      0         1
3  35.0  53.1000      1      0         1
4  35.0   8.0500      0      0         0

In [ ]:
df['Family']=df['Parch']+df['SibSp']

In [ ]:
df.head()

    Age     Fare  SibSp  Parch  Survived  Family
0  22.0   7.2500      1      0         0       1
1  38.0  71.2833      1      0         1       1
2  26.0   7.9250      0      0         1       0
3  35.0  53.1000      1      0         1       1
4  35.0   8.0500      0      0         0       0

In [ ]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [ ]:
df.head()

    Age     Fare  Survived  Family
0  22.0   7.2500         0       1
1  38.0  71.2833         1       1
2  26.0   7.9250         1       0
3  35.0  53.1000         1       1
4  35.0   8.0500         0       0

In [ ]:
X=df.drop(columns=['Survived'])
y=df['Survived']

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2,random_state=42)
xtrain

      Age      Fare  Family
328  31.0   20.5250       2
73   26.0   14.4542       1
253  30.0   16.1000       1
719  33.0    7.7750       0
666  25.0   13.0000       0
..    ...       ...     ...
92   46.0   61.1750       1
134  25.0   13.0000       0
337  41.0  134.5000       0
548  33.0   20.5250       2
130  33.0    7.8958       0

[571 rows x 3 columns]

In [ ]:
ytrain

328    1
73     0
253    0
719    0
666    0
      ..
92     0
134    0
337    1
548    0
130    0
Name: Survived, Length: 571, dtype: int64

In [ ]:
clf=DecisionTreeClassifier()

In [ ]:
clf.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [ ]:
ypred=clf.predict(xtest)

In [ ]:
accuracy_score(ytest,ypred)

0.6363636363636364

In [ ]:
np.mean(cross_val_score(clf,X,y, scoring='accuracy',cv=10))

np.float64(0.6415297339593115)

#after applying Binarization

In [ ]:
tnf=ColumnTransformer([('bin',Binarizer(copy=False),['Family'])],remainder='passthrough')

In [ ]:
xtrain_trans=tnf.fit_transform(xtrain)
xtest_trans=tnf.transform(xtest)

In [ ]:
xtrain_trans

array([[  1.    ,  31.    ,  20.525 ],
       [  1.    ,  26.    ,  14.4542],
       [  1.    ,  30.    ,  16.1   ],
       ...,
       [  0.    ,  41.    , 134.5   ],
       [  1.    ,  33.    ,  20.525 ],
       [  0.    ,  33.    ,   7.8958]])

In [ ]:
pd.DataFrame(xtrain_trans,columns=['Age','Fare','Family'])

     Age  Fare    Family
0    1.0  31.0   20.5250
1    1.0  26.0   14.4542
2    1.0  30.0   16.1000
3    0.0  33.0    7.7750
4    0.0  25.0   13.0000
..   ...   ...       ...
566  1.0  46.0   61.1750
567  0.0  25.0   13.0000
568  0.0  41.0  134.5000
569  1.0  33.0   20.5250
570  0.0  33.0    7.8958

[571 rows x 3 columns]

In [ ]:
clf=DecisionTreeClassifier()

In [ ]:
clf.fit(xtrain_trans,ytrain)
ypred1=clf.predict(xtest_trans)
accuracy_score(ytest,ypred1)

0.6083916083916084

In [ ]:
X_trf = tnf.fit_transform(X)
np.mean(cross_val_score(clf,X_trf,y,cv=10,scoring='accuracy'))

np.float64(0.6289906103286385)