<a href="https://colab.research.google.com/github/souravk03/Machine-Learning-404/blob/main/Feature_Engineering_IV_(Nominal_encoding_One_Hot_Encoding).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import pandas as pd

In [13]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/cars.csv')
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

## One hot encoding

### DUmmy variable are created after One hot encoding and there is some collinerity between the new dummy variable created and to avoid this **Dummy variable trap or Multicollinearity**, we have to drop the first dummy column after One hot encoding

In [14]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [15]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

# One Hot Encoding using pandas

In [24]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,owner,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,Maruti,145500,First Owner,450000,False,True,False,False
1,Skoda,120000,Second Owner,370000,False,True,False,False
2,Honda,140000,Third Owner,158000,False,False,False,True
3,Hyundai,127000,First Owner,225000,False,True,False,False
4,Maruti,120000,First Owner,130000,False,False,False,True
...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,First Owner,320000,False,False,False,True
8124,Hyundai,119000,Fourth & Above Owner,135000,False,True,False,False
8125,Maruti,120000,First Owner,382000,False,True,False,False
8126,Tata,25000,First Owner,290000,False,True,False,False
8127,Tata,25000,First Owner,290000,False,True,False,False

#### as you can see from the above dataframe there are 12 columns are created where since there are 4 categories in the fuel 4 new dummy vehicle are created for fuel and other 4 are from owners. now there is problem of **Multicollinerity arises as there is some mathematical relation between the input data to remove these problem we have to delete the first column of dummy variable**

# K-1 Encoding where K is categories

In [27]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True,dtype='int32') #default dummy variables are bool

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

#One Hot Encoding using SKLearn

In [28]:
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [71]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2)

In [72]:
xtrain

              brand  km_driven    fuel                 owner
5323         Toyota     285000  Diesel           Third Owner
1676  Mercedes-Benz     110000  Diesel           Third Owner
1213         Maruti      90000  Diesel          Second Owner
3303      Chevrolet     198000  Diesel           First Owner
199          Maruti      70000  Diesel           First Owner
...             ...        ...     ...                   ...
1525         Maruti     120000  Diesel  Fourth & Above Owner
549          Maruti      32000  Diesel           First Owner
3768         Maruti      70000  Diesel          Second Owner
5906         Maruti      43000  Petrol           First Owner
6963          Volvo      20000  Diesel           First Owner

[6502 rows x 4 columns]

In [73]:
from sklearn.preprocessing import OneHotEncoder
Ohe=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [74]:
xtrain_new=Ohe.fit_transform(xtrain[['fuel','owner']])

In [75]:
xtest_new=Ohe.transform(xtest[['fuel','owner']])

In [76]:
xtrain_new.shape

(6502, 7)

In [77]:
np.hstack((xtrain[['brand','km_driven']].values,xtrain_new))

array([['Toyota', 285000, 1, ..., 0, 0, 1],
       ['Mercedes-Benz', 110000, 1, ..., 0, 0, 1],
       ['Maruti', 90000, 1, ..., 1, 0, 0],
       ...,
       ['Maruti', 70000, 1, ..., 1, 0, 0],
       ['Maruti', 43000, 0, ..., 0, 0, 0],
       ['Volvo', 20000, 1, ..., 0, 0, 0]], dtype=object)

#Onehot Encoding with top categories

In [95]:
counts = df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [96]:
df['brand'].nunique()

32

In [98]:
threshold = 100
counts[counts <= threshold].index

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Ambassador',
       'Kia', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [81]:
repl = counts[counts <= threshold].index

In [89]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'),dtype=np.int32).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
7311,0,0,0,0,1,0,0,0,0,0,0,0,0
6350,0,0,0,0,0,0,1,0,0,0,0,0,0
6575,0,0,0,0,0,0,0,0,0,0,0,0,1
5244,0,0,0,1,0,0,0,0,0,0,0,0,0
7003,0,0,0,0,0,1,0,0,0,0,0,0,0